"""Registry APIs for FungMod plug-and-play metadata."""

from fungal_model.core.value_spec import ValueSpec, ValueSpecError
from fungal_model.registry.loaders import (
    RegistryLoadError,
    RegistryRecordType,
    load_registry,
    load_registry_record_mapping,
)
from fungal_model.registry.records import (
    CaseTemplateRecord,
    EnzymeClassRecord,
    EnvironmentRecord,
    FungusRecord,
    ParameterRecord,
    ProductMapRecord,
    PARAMETER_ALLOWED_USE_EXPLORATORY,
    PARAMETER_ALLOWED_USE_EXPLORATORY_SCREENING,
    PARAMETER_ALLOWED_USE_GAP_ANALYSIS_ONLY,
    PARAMETER_ALLOWED_USE_SCIENTIFIC,
    PARAMETER_ALLOWED_USE_SOFTWARE_TESTS_ONLY,
    PARAMETER_ALLOWED_USE_STORAGE_ONLY,
    PROCESS_COMPATIBILITY_SCOPE_COMPONENT,
    PROCESS_COMPATIBILITY_SCOPE_STANDALONE,
    ProcessComponentBinding,
    ProcessCompatibilityRecord,
    RegistryRecord,
    SubstrateRecord,
)
from fungal_model.registry.resolver import (
    AmbiguousResolutionError,
    RegistryResolver,
    ResolutionError,
    ResolvedRecord,
)
from fungal_model.registry.store import FungModRegistry, RegistryLookupError, RegistryValidationError

__all__ = [
    "AmbiguousResolutionError",
    "CaseTemplateRecord",
    "EnzymeClassRecord",
    "EnvironmentRecord",
    "FungModRegistry",
    "FungusRecord",
    "ParameterRecord",
    "ProductMapRecord",
    "PARAMETER_ALLOWED_USE_EXPLORATORY",
    "PARAMETER_ALLOWED_USE_EXPLORATORY_SCREENING",
    "PARAMETER_ALLOWED_USE_GAP_ANALYSIS_ONLY",
    "PARAMETER_ALLOWED_USE_SCIENTIFIC",
    "PARAMETER_ALLOWED_USE_SOFTWARE_TESTS_ONLY",
    "PARAMETER_ALLOWED_USE_STORAGE_ONLY",
    "PROCESS_COMPATIBILITY_SCOPE_COMPONENT",
    "PROCESS_COMPATIBILITY_SCOPE_STANDALONE",
    "ProcessComponentBinding",
    "ProcessCompatibilityRecord",
    "RegistryResolver",
    "RegistryLoadError",
    "RegistryRecordType",
    "RegistryLookupError",
    "RegistryRecord",
    "RegistryValidationError",
    "ResolutionError",
    "ResolvedRecord",
    "SubstrateRecord",
    "ValueSpec",
    "ValueSpecError",
    "load_registry",
    "load_registry_record_mapping",
]
