"""The paper's tables are generated from the recorded results and the committed copies match them."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

import pytest

from fungal_model.research import paper_tables
from fungal_model.research.gelain_culture import CultureBenchmarkError

ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / paper_tables.PAPER_TABLES_DIR


def test_committed_tables_and_manifest_match_the_recorded_results() -> None:
    assert paper_tables.check_tables(ROOT) == []


def test_regenerating_the_tables_elsewhere_is_byte_identical(tmp_path: Path) -> None:
    manifest = paper_tables.write_tables(ROOT, tmp_path)
    for name, entry in manifest["tables"].items():
        assert (tmp_path / entry["file"]).read_bytes() == (TABLES / entry["file"]).read_bytes(), name
    assert json.loads((tmp_path / paper_tables.MANIFEST_NAME).read_text(encoding="utf-8")) == json.loads(
        (TABLES / paper_tables.MANIFEST_NAME).read_text(encoding="utf-8")
    )


def test_manifest_digests_name_the_files_on_disk() -> None:
    manifest = json.loads((TABLES / paper_tables.MANIFEST_NAME).read_text(encoding="utf-8"))
    assert set(manifest["tables"]) == {builder(ROOT).name for builder in paper_tables.TABLE_BUILDERS}
    for entry in manifest["tables"].values():
        assert entry["sources"], entry["file"]
        for source, digest in entry["sources"].items():
            assert hashlib.sha256((ROOT / source).read_bytes()).hexdigest() == digest, source


def test_every_table_is_cited_by_the_paper() -> None:
    text = (ROOT / "paper" / "paper.md").read_text(encoding="utf-8")
    manifest = json.loads((TABLES / paper_tables.MANIFEST_NAME).read_text(encoding="utf-8"))
    for entry in manifest["tables"].values():
        assert f"tables/{entry['file']}" in text, entry["file"]


def test_key_numbers_agree_with_the_tables_they_summarise() -> None:
    manifest = json.loads((TABLES / paper_tables.MANIFEST_NAME).read_text(encoding="utf-8"))
    stage_a = manifest["tables"]["table_3_criticism_stage_a"]["key_numbers"]
    assert stage_a["models"]["M2_soluble_product_pool"]["primary"]["screen_passed"] is True
    assert stage_a["models"]["M1_induction_state"]["primary"]["screen_passed"] is False
    cross = manifest["tables"]["table_5_cross_solver"]["key_numbers"]
    assert cross["outcome"] == "reproduced" and cross["optimum_relative_difference"] <= 1e-3
    bayes = manifest["tables"]["table_2_identifiability"]["key_numbers"]
    assert bayes["converged"] is True and bayes["identified_count"] == 5
    stage_b = manifest["tables"]["table_4_criticism_stage_b"]["key_numbers"]
    assert stage_b["M2_soluble_product_pool"]["outcome"] == "improves fit but unidentified (R1, not R3)"
    joint = manifest["tables"]["table_1_joint_holdouts"]["key_numbers"]
    assert joint["validated"] is False and joint["folds_numerically_checked"] == joint["folds"]
    text = (TABLES / "table_5_cross_solver.md").read_text(encoding="utf-8")
    assert "| Outcome | `reproduced` |" in text


def test_table_builders_refuse_missing_results(tmp_path: Path) -> None:
    with pytest.raises(CultureBenchmarkError, match="missing"):
        paper_tables.joint_benchmark_table(tmp_path)
    with pytest.raises(CultureBenchmarkError):
        paper_tables.criticism_stage_b_table(tmp_path)


def test_check_tables_reports_a_tampered_table(tmp_path: Path) -> None:
    paper_tables.write_tables(ROOT, tmp_path)
    assert paper_tables.check_tables(ROOT, tmp_path) == []
    target = tmp_path / "table_5_cross_solver.md"
    target.write_text(target.read_text(encoding="utf-8").replace("reproduced", "edited"), encoding="utf-8")
    problems = paper_tables.check_tables(ROOT, tmp_path)
    assert len(problems) == 1 and "table_5_cross_solver.md" in problems[0]
    (tmp_path / paper_tables.MANIFEST_NAME).unlink()
    assert any("manifest.json is missing" in problem for problem in paper_tables.check_tables(ROOT, tmp_path))


def test_generated_tables_carry_the_generator_marker() -> None:
    for path in sorted(TABLES.glob("*.md")):
        first = path.read_text(encoding="utf-8").splitlines()[0]
        assert re.match(r"<!-- generated by scripts/reproduce_paper.py tables; do not edit -->", first), path
