"""FungMod: traceable models for fungal and enzyme-mediated substrate degradation."""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("fungal-model")
except PackageNotFoundError:  # pragma: no cover - editable tree before install
    __version__ = "0.1.0"

from fungal_model.core.assumptions import Assumption
from fungal_model.core.errors import (
    IncompatibleUnitsError,
    InvalidMechanismError,
    MissingParameterError,
    MissingProcessError,
    ModelAssemblyError,
)
from fungal_model.core.parameters import Parameter, ParameterSet
from fungal_model.core.simulation import SolverSettings
from fungal_model.entities import Environment
from fungal_model.entities import Enzyme
from fungal_model.api import (
    AVAILABLE_SOURCE_PROVIDERS,
    CurationDecision,
    CurationError,
    CurationResult,
    CuratorAuthoredParameterResult,
    DegradationScreenResult,
    EnvironmentCase,
    EnvironmentGrid,
    ProspectiveRegistryFile,
    LoadedCurationBundle,
    ParameterRecordAuthoringError,
    RegistryPromotionAppliedFile,
    RegistryPromotionApplyError,
    RegistryPromotionApplyResult,
    RegistryPromotionCandidate,
    RegistryPromotionPlan,
    RegistryPromotionPlanError,
    RegistryPromotionPlanWriteResult,
    SourceProviderError,
    VirtualExperiment,
    VirtualExperimentError,
    apply_registry_promotion,
    author_parameter_record,
    environment_grid,
    load_curation_bundle,
    plan_registry_promotion,
    review_source_proposal,
    source_proposal,
    virtual_experiment,
)
from fungal_model.fungi.base import Fungus
from fungal_model.geometry import (
    Film1DGeometry,
    Geometry,
    ParticleGeometry,
    PorousMediumGeometry,
    SlabGeometry,
    WellMixedGeometry,
)
from fungal_model.io import (
    ConfigReference,
    EntityConfigRefs,
    EntropyProductionRateTimeseriesConfig,
    GeometryLoaderRegistry,
    InitialStateConfig,
    load_enzyme,
    load_environment,
    load_fungus,
    load_geometry,
    load_model_config,
    load_parameter_set,
    load_product_map,
    load_substrate,
    merge_parameter_sets,
    ModelConfig,
    OutputConfig,
    ParameterMergeError,
    ParameterSetConfig,
    ProcessConfig,
    ProductMapRegistry,
    RegistryLookupError,
    SubstrateLoaderRegistry,
    TimeConfig,
    ValidatorConfig,
    ValidatorRegistry,
)
from fungal_model.registry import (
    AmbiguousResolutionError,
    RegistryResolver,
    ResolutionError,
    ResolvedRecord,
)
from fungal_model.modifiers import (
    OxygenModifier,
    PHModifier,
    ProductInhibitionModifier,
    TemperatureModifier,
    WaterActivityModifier,
)
from fungal_model.processes import (
    AssembledModel,
    AssemblyReport,
    BuildDecision,
    ModelAssemblyContext,
    ModelBuilder,
    ParameterRequirement,
    Process,
    ProcessBuildContext,
    ProcessFactory,
    ProcessLibrary,
    ProcessRegistry,
    RateModifierProcess,
    StateVariableSpec,
    ValidityDomain,
    FirstOrderDecayProcess,
    FirstOrderFactory,
    HomogeneousMichaelisMentenFactory,
    HomogeneousMichaelisMentenProcess,
    MassActionFactory,
    MassActionProcess,
    AccessibleSitePool,
    AccessibleSurfaceAreaModel,
    BondCleavageProcess,
    EquilibriumSurfaceCoverageModel,
    LangmuirAdsorptionModel,
    ProductReleaseMap,
    SurfaceCatalysisFactory,
    SurfaceCatalysisModel,
    SurfaceCatalysisProcess,
    CompatibilityIssue,
)
from fungal_model.results import SimulationResult
from fungal_model.solvers import ProcessODESolver, RunRequest
from fungal_model.substrates.base import Substrate
from fungal_model.validation import InvalidDataMaturityError, MaturityIssue
from fungal_model.workflows import (
    ConfiguredInputLoader,
    ConfiguredModelExecutionError,
    ConfiguredModelRunReport,
    ConfiguredModelRunner,
    ConfiguredOutputWriter,
    ConfiguredProcessAssembler,
    run_configured_model,
)

__all__ = [
    "AVAILABLE_SOURCE_PROVIDERS",
    "CurationDecision",
    "CurationError",
    "CurationResult",
    "CuratorAuthoredParameterResult",
    "LoadedCurationBundle",
    "AssembledModel",
    "AssemblyReport",
    "Assumption",
    "AccessibleSitePool",
    "AccessibleSurfaceAreaModel",
    "AmbiguousResolutionError",
    "BondCleavageProcess",
    "BuildDecision",
    "CompatibilityIssue",
    "ConfigReference",
    "ConfiguredInputLoader",
    "ConfiguredModelExecutionError",
    "ConfiguredModelRunReport",
    "ConfiguredModelRunner",
    "ConfiguredOutputWriter",
    "ConfiguredProcessAssembler",
    "DegradationScreenResult",
    "Enzyme",
    "EntityConfigRefs",
    "EntropyProductionRateTimeseriesConfig",
    "EquilibriumSurfaceCoverageModel",
    "Environment",
    "EnvironmentCase",
    "EnvironmentGrid",
    "environment_grid",
    "Film1DGeometry",
    "Fungus",
    "Geometry",
    "GeometryLoaderRegistry",
    "FirstOrderDecayProcess",
    "FirstOrderFactory",
    "HomogeneousMichaelisMentenProcess",
    "HomogeneousMichaelisMentenFactory",
    "LangmuirAdsorptionModel",
    "InitialStateConfig",
    "IncompatibleUnitsError",
    "InvalidDataMaturityError",
    "InvalidMechanismError",
    "load_enzyme",
    "load_environment",
    "load_fungus",
    "load_geometry",
    "load_curation_bundle",
    "load_model_config",
    "load_parameter_set",
    "load_product_map",
    "load_substrate",
    "merge_parameter_sets",
    "MassActionProcess",
    "MassActionFactory",
    "MissingParameterError",
    "MissingProcessError",
    "MaturityIssue",
    "ModelAssemblyContext",
    "ModelAssemblyError",
    "ModelBuilder",
    "ModelConfig",
    "OutputConfig",
    "Parameter",
    "ParameterRecordAuthoringError",
    "ParameterMergeError",
    "ParameterRequirement",
    "ParameterSet",
    "ParameterSetConfig",
    "ParticleGeometry",
    "apply_registry_promotion",
    "author_parameter_record",
    "plan_registry_promotion",
    "PorousMediumGeometry",
    "Process",
    "ProcessBuildContext",
    "ProcessFactory",
    "ProcessConfig",
    "ProcessLibrary",
    "ProcessRegistry",
    "ProcessODESolver",
    "ProspectiveRegistryFile",
    "ProductMapRegistry",
    "ProductReleaseMap",
    "RateModifierProcess",
    "RegistryLookupError",
    "RegistryPromotionAppliedFile",
    "RegistryPromotionApplyError",
    "RegistryPromotionApplyResult",
    "RegistryPromotionCandidate",
    "RegistryPromotionPlan",
    "RegistryPromotionPlanError",
    "RegistryPromotionPlanWriteResult",
    "RegistryResolver",
    "ResolutionError",
    "ResolvedRecord",
    "RunRequest",
    "OxygenModifier",
    "PHModifier",
    "ProductInhibitionModifier",
    "SimulationResult",
    "SlabGeometry",
    "SolverSettings",
    "StateVariableSpec",
    "SourceProviderError",
    "Substrate",
    "SubstrateLoaderRegistry",
    "SurfaceCatalysisModel",
    "SurfaceCatalysisFactory",
    "SurfaceCatalysisProcess",
    "TemperatureModifier",
    "TimeConfig",
    "ValidityDomain",
    "ValidatorConfig",
    "ValidatorRegistry",
    "VirtualExperiment",
    "VirtualExperimentError",
    "WaterActivityModifier",
    "WellMixedGeometry",
    "run_configured_model",
    "review_source_proposal",
    "source_proposal",
    "virtual_experiment",
    "__version__",
]
