"""Researcher-facing FungMod virtual-experiment API."""

from fungal_model.api.curation import (
    CurationDecision,
    CurationError,
    CurationResult,
    LoadedCurationBundle,
    load_curation_bundle,
    review_source_proposal,
)
from fungal_model.api.environment_grid import EnvironmentCase, EnvironmentGrid, environment_grid
from fungal_model.api.parameter_conversion import (
    PARAMETER_CONVERSION_REGISTRY_SCHEMA_VERSION,
    PINT_DECIMAL_PLACES_HALF_EVEN_12_V1,
    ParameterConversionError,
    ParameterConversionMethod,
    ParameterConversionRegistry,
    default_parameter_conversion_registry,
)
from fungal_model.api.parameter_record_authoring import (
    CuratorAuthoredParameterResult,
    ParameterRecordAuthoringError,
    author_parameter_record,
)
from fungal_model.api.registry_promotion import (
    ProspectiveRegistryFile,
    RegistryPromotionAppliedFile,
    RegistryPromotionApplyError,
    RegistryPromotionApplyResult,
    RegistryPromotionCandidate,
    RegistryPromotionPlan,
    RegistryPromotionPlanError,
    RegistryPromotionPlanWriteResult,
    apply_registry_promotion,
    plan_registry_promotion,
)
from fungal_model.api.registry_record_authoring import (
    REGISTRY_RECORD_AUTHORING_ALLOWED_MATURITIES,
    REGISTRY_RECORD_AUTHORING_PROVENANCE_KEY,
    REGISTRY_RECORD_AUTHORING_SCHEMA_VERSION,
    REGISTRY_RECORD_AUTHORING_WORKFLOW,
    SUPPORTED_AUTHORED_REGISTRY_RECORD_TYPES,
    CuratorAuthoredRegistryResult,
    RegistryRecordAuthoringError,
    author_registry_records,
)
from fungal_model.api.source_provider import (
    AVAILABLE_SOURCE_PROVIDERS,
    SourceProviderError,
    source_proposal,
)
from fungal_model.api.virtual_experiment import (
    DegradationScreenResult,
    VirtualExperiment,
    VirtualExperimentError,
    VirtualExperimentMode,
    virtual_experiment,
)

__all__ = [
    "CurationDecision",
    "CurationError",
    "CurationResult",
    "LoadedCurationBundle",
    "PARAMETER_CONVERSION_REGISTRY_SCHEMA_VERSION",
    "PINT_DECIMAL_PLACES_HALF_EVEN_12_V1",
    "ParameterConversionError",
    "ParameterConversionMethod",
    "ParameterConversionRegistry",
    "CuratorAuthoredParameterResult",
    "CuratorAuthoredRegistryResult",
    "DegradationScreenResult",
    "AVAILABLE_SOURCE_PROVIDERS",
    "EnvironmentCase",
    "EnvironmentGrid",
    "environment_grid",
    "default_parameter_conversion_registry",
    "apply_registry_promotion",
    "author_parameter_record",
    "plan_registry_promotion",
    "load_curation_bundle",
    "ProspectiveRegistryFile",
    "RegistryPromotionAppliedFile",
    "RegistryPromotionApplyError",
    "RegistryPromotionApplyResult",
    "RegistryPromotionCandidate",
    "RegistryPromotionPlan",
    "RegistryPromotionPlanError",
    "RegistryPromotionPlanWriteResult",
    "ParameterRecordAuthoringError",
    "REGISTRY_RECORD_AUTHORING_ALLOWED_MATURITIES",
    "REGISTRY_RECORD_AUTHORING_PROVENANCE_KEY",
    "REGISTRY_RECORD_AUTHORING_SCHEMA_VERSION",
    "REGISTRY_RECORD_AUTHORING_WORKFLOW",
    "RegistryRecordAuthoringError",
    "SUPPORTED_AUTHORED_REGISTRY_RECORD_TYPES",
    "author_registry_records",
    "review_source_proposal",
    "source_proposal",
    "SourceProviderError",
    "VirtualExperiment",
    "VirtualExperimentError",
    "VirtualExperimentMode",
    "virtual_experiment",
]
