"""Figures of the software paper, generated from the recorded study results with a digest manifest.

Each figure is drawn from numbers in checksummed result files under
``data/benchmarks`` (and, for the measured points, the reviewed literature
datasets under ``data/experiments``). For every figure this module writes the
plotted numbers as JSON next to the SVG (for reading in a browser) and the PDF
(included by the LaTeX manuscript), and a manifest that records the source
files with their SHA-256 digests and the key numbers the caption quotes. The
JSON data and the manifest are compared byte for byte by ``check_figures``;
the SVG and the PDF are regenerated by the same matplotlib call but compared
only for presence and the generator marker, because their bytes depend on the
matplotlib version.

Nothing here computes science: it reads recorded results and plots them.
"""

from __future__ import annotations

import json
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np

from fungal_model.research.gelain_culture import CultureBenchmarkError
from fungal_model.research.gelain_joint import load_joint_cultures
from fungal_model.research.paper_tables import BAYESIAN_RESULT, CRITICISM_STAGE_A, CROSS_SOLVER, _read_json, file_digest

PAPER_FIGURES_DIR = Path("paper/figures")
MANIFEST_NAME = "manifest.json"
GENERATOR = "fungal_model.research.paper_figures (scripts/reproduce_paper.py tables)"
PDF_MARKER = GENERATOR.split(" ", 1)[0].encode("ascii")  # PDF string literals escape the parentheses
V2_RESULTS = Path("data/benchmarks/gelain_2020_v2/results")
V2_FOLDS = V2_RESULTS / "folds.json"
CRITICISM_PLAN = Path("data/benchmarks/gelain_2020_criticism/plan.json")
DATASET_DIR = Path("data/experiments/literature/gelain_2020_t_harzianum")
HOLDOUT_MODELS = ("hydrolysis", "published")
OBSERVABLE_LABELS = {
    "biomass": "biomass (g/L)",
    "substrate": "cellulose (g/L)",
    "cellulase_activity": "filter-paper activity (FPU/L)",
    "beta_glucosidase_activity": "beta-glucosidase activity (U/L)",
}
MODEL_LABELS = {
    "hydrolysis": "activity-driven hydrolysis candidate",
    "published": "published equations (re-fitted)",
    "M0_baseline": "M0 baseline",
    "M1_induction_state": "M1 induction state",
    "M2_soluble_product_pool": "M2 soluble product pool",
    "M3_conversion_dependent_accessibility": "M3 accessibility",
}


@dataclass(frozen=True)
class PaperFigure:
    """One figure of the paper: the numbers it plots, how to draw them and where they came from."""

    name: str
    title: str
    caption: str
    data: dict[str, Any]
    draw: Callable[[dict[str, Any], Any], None]
    sources: dict[str, str] = field(default_factory=dict)
    key_numbers: dict[str, Any] = field(default_factory=dict)

    @property
    def file_name(self) -> str:
        return f"{self.name}.svg"

    @property
    def pdf_file_name(self) -> str:
        return f"{self.name}.pdf"

    @property
    def data_file_name(self) -> str:
        return f"{self.name}.json"

    def rendered_data(self) -> str:
        payload = {"generator": GENERATOR, "title": self.title, "caption": self.caption, "data": self.data}
        return json.dumps(payload, indent=2, allow_nan=False) + "\n"


def _sources(root: Path, paths: Sequence[Path]) -> dict[str, str]:
    return {path.as_posix(): file_digest(root / path) for path in paths}


def _cellulose_measurements(root: Path) -> list[dict[str, Any]]:
    """The published cellulose means as plain lists, one entry per loading, in condition order."""

    measurements = []
    for culture in load_joint_cultures(root):
        if culture.design.family != "cellulose":
            continue
        values = np.asarray(culture.values, dtype=float)
        measurements.append(
            {
                "condition": culture.design.condition_id,
                "loading_g_l": float(culture.design.initial_substrate.to("gram/liter").magnitude),
                "times_h": np.asarray(culture.design.times.to("hour").magnitude, dtype=float).tolist(),
                "observables": list(culture.names),
                "observations": {name: values[:, index].tolist() for index, name in enumerate(culture.names)},
            }
        )
    if not measurements:
        raise CultureBenchmarkError("No cellulose conditions were loaded; the figures need the three loadings.")
    return measurements


def _dataset_paths(measurements: Sequence[Mapping[str, Any]]) -> list[Path]:
    return [DATASET_DIR / f"{entry['condition']}.yml" for entry in measurements]


def _scatter_measurements(ax: Any, entry: Mapping[str, Any], observable: str) -> None:
    ax.scatter(entry["times_h"], entry["observations"][observable], color="black", s=16, zorder=5, label="published means")


def _finish_grid(fig: Any, axes: Any, measurements: Sequence[Mapping[str, Any]], observables: Sequence[str]) -> None:
    for column, entry in enumerate(measurements):
        axes[0, column].set_title(f"held out: {entry['loading_g_l']:g} g/L cellulose", fontsize=10)
        for row, observable in enumerate(observables):
            ax = axes[row, column]
            ax.set_ylabel(OBSERVABLE_LABELS.get(observable, observable), fontsize=8)
            ax.tick_params(labelsize=8)
            if row == len(observables) - 1:
                ax.set_xlabel("time (h)", fontsize=8)
    axes[0, 0].legend(fontsize=7)
    fig.tight_layout()


# ---------------------------------------------------------------------------
# Figure 1: whole-condition holdouts of the joint benchmark on cellulose
# ---------------------------------------------------------------------------


def holdout_figure(root: Path) -> PaperFigure:
    measurements = _cellulose_measurements(root)
    folds = _read_json(root / V2_FOLDS)
    frozen_paths: list[Path] = []
    for entry in measurements:
        entry["predictions"] = {}
        for model in HOLDOUT_MODELS:
            matches = [
                fold
                for fold in folds
                if fold["condition"] == entry["condition"] and fold["model"] == model and fold["scenario"] == "primary"
            ]
            if len(matches) != 1 or not matches[0]["fit"]["success"]:
                raise CultureBenchmarkError(
                    f"Expected one successful primary fold of {model!r} for {entry['condition']!r}; found {len(matches)}."
                )
            frozen_path = V2_RESULTS / matches[0]["frozen_prediction_file"]
            frozen = _read_json(root / frozen_path)
            frozen_paths.append(frozen_path)
            if list(frozen["observables"]) != entry["observables"]:
                raise CultureBenchmarkError(f"{frozen_path} does not carry the measured observables in order.")
            predictions = np.asarray(frozen["predictions"], dtype=float)
            entry["predictions"][model] = {
                "times_h": [float(value) for value in frozen["times_h"]],
                "values": {name: predictions[:, index].tolist() for index, name in enumerate(frozen["observables"])},
                "normalized_mse": matches[0]["score"]["normalized_mse"],
            }
    observables = measurements[0]["observables"]
    data = {"observables": observables, "models": list(HOLDOUT_MODELS), "conditions": measurements}

    def draw(data: dict[str, Any], fig: Any) -> None:
        axes = fig.subplots(len(data["observables"]), len(data["conditions"]), squeeze=False)
        for column, entry in enumerate(data["conditions"]):
            for row, observable in enumerate(data["observables"]):
                ax = axes[row, column]
                _scatter_measurements(ax, entry, observable)
                for model in data["models"]:
                    prediction = entry["predictions"][model]
                    ax.plot(prediction["times_h"], prediction["values"][observable], label=MODEL_LABELS.get(model, model))
        _finish_grid(fig, axes, data["conditions"], data["observables"])

    return PaperFigure(
        name="figure_1_cellulose_holdouts",
        title="Whole-condition holdouts of the joint benchmark on the three cellulose loadings",
        caption=(
            "Published means (points) against the frozen held-out predictions (lines) of the activity-driven "
            "hydrolysis candidate and the re-fitted published equations, each loading predicted from a fit to the "
            "other two (primary scenario). Measurement error is unknown; the points are published means."
        ),
        data=data,
        draw=draw,
        sources=_sources(root, [V2_FOLDS, *frozen_paths, *_dataset_paths(measurements)]),
        key_numbers={
            "conditions": len(measurements),
            "models": list(HOLDOUT_MODELS),
            "mean_normalized_mse_by_model": {
                model: {
                    entry["condition"]: entry["predictions"][model]["normalized_mse"] for entry in measurements
                }
                for model in HOLDOUT_MODELS
            },
        },
    )


# ---------------------------------------------------------------------------
# Figure 2: posterior predictive bands of the Bayesian study
# ---------------------------------------------------------------------------


def posterior_predictive_figure(root: Path) -> PaperFigure:
    result = _read_json(root / BAYESIAN_RESULT)
    predictive = result["posterior_predictive"]
    measurements = _cellulose_measurements(root)
    for entry in measurements:
        bands = predictive["conditions"].get(entry["condition"])
        if bands is None:
            raise CultureBenchmarkError(f"The Bayesian result carries no posterior predictive for {entry['condition']!r}.")
        if bands["band_layout"] != "quantile_bands[observable][quantile_index][time_index]":
            raise CultureBenchmarkError(f"Unexpected posterior predictive band layout {bands['band_layout']!r}.")
        if list(bands["observables"]) != entry["observables"]:
            raise CultureBenchmarkError("The posterior predictive observables differ from the measured ones.")
        entry["bands"] = {
            "times_h": [float(value) for value in bands["times"]],
            "quantiles": {name: bands["quantile_bands"][name] for name in entry["observables"]},
            "successful_draws": int(bands["successful_draws"]),
        }
    data = {
        "observables": measurements[0]["observables"],
        "quantiles": [float(value) for value in predictive["quantiles"]],
        "includes_measurement_noise": bool(predictive["includes_measurement_noise"]),
        "conditions": measurements,
    }

    def draw(data: dict[str, Any], fig: Any) -> None:
        axes = fig.subplots(len(data["observables"]), len(data["conditions"]), squeeze=False)
        low, mid, high = 0, len(data["quantiles"]) // 2, len(data["quantiles"]) - 1
        for column, entry in enumerate(data["conditions"]):
            bands = entry["bands"]
            for row, observable in enumerate(data["observables"]):
                ax = axes[row, column]
                quantiles = bands["quantiles"][observable]
                ax.fill_between(
                    bands["times_h"], quantiles[low], quantiles[high], color="tab:blue", alpha=0.25,
                    label=f"{100 * data['quantiles'][low]:g} to {100 * data['quantiles'][high]:g} percent band",
                )
                ax.plot(bands["times_h"], quantiles[mid], color="tab:blue", label="posterior median")
                _scatter_measurements(ax, entry, observable)
        _finish_grid(fig, axes, data["conditions"], data["observables"])

    return PaperFigure(
        name="figure_2_posterior_predictive",
        title="Posterior predictive bands of the hydrolysis candidate on the cellulose loadings",
        caption=(
            "Posterior median and the 5 to 95 percent band of the model prediction over the posterior samples of "
            "the nine registry constants (all three loadings fitted; the bands exclude measurement noise), with "
            "the published means as points."
        ),
        data=data,
        draw=draw,
        sources=_sources(root, [BAYESIAN_RESULT, *_dataset_paths(measurements)]),
        key_numbers={
            "draws": int(predictive["draws"]),
            "quantiles": data["quantiles"],
            "includes_measurement_noise": data["includes_measurement_noise"],
            "successful_draws": {entry["condition"]: entry["bands"]["successful_draws"] for entry in measurements},
        },
    )


# ---------------------------------------------------------------------------
# Figure 3: the stage A holdout screen of the model-criticism study
# ---------------------------------------------------------------------------


def criticism_screen_figure(root: Path) -> PaperFigure:
    comparison = _read_json(root / CRITICISM_STAGE_A)
    plan = _read_json(root / CRITICISM_PLAN)
    screen = plan["stage_A_least_squares"]["screen"]
    reference = screen["reference"]
    models = comparison["models"]
    if reference not in models:
        raise CultureBenchmarkError(f"The stage A comparison lacks the screen reference {reference!r}.")
    scenarios: dict[str, Any] = {}
    for scenario in ("primary", "correlated_assumption"):
        baseline = models[reference]["scenarios"][scenario]["pooled_normalized_mse"]
        entries = {}
        for model_id, record in models.items():
            if model_id == reference:
                continue
            row = record["scenarios"][scenario]
            pooled = row["pooled_normalized_mse"]
            entries[model_id] = {
                "relative_change_by_observable": {
                    observable: float(pooled[observable] / baseline[observable] - 1.0) for observable in baseline
                },
                "relative_improvement": float(row["screen"]["relative_improvement"]),
                "passed": bool(row["screen"]["passed"]),
                "reasons": list(row["screen"]["reasons"]),
            }
        scenarios[scenario] = {"baseline_pooled_normalized_mse": baseline, "models": entries}
    data = {
        "reference": reference,
        "observables": list(models[reference]["scenarios"]["primary"]["pooled_normalized_mse"]),
        "minimum_relative_improvement": float(screen["minimum_relative_cv_improvement"]),
        "maximum_observable_worsening": float(screen["maximum_observable_worsening"]),
        "scenarios": scenarios,
    }

    def draw(data: dict[str, Any], fig: Any) -> None:
        axes = fig.subplots(1, len(data["scenarios"]), squeeze=False, sharey=True)
        observables = data["observables"]
        width = 0.8 / (len(observables) + 1)
        for column, (scenario, block) in enumerate(data["scenarios"].items()):
            ax = axes[0, column]
            model_ids = list(block["models"])
            positions = np.arange(len(model_ids))
            for index, observable in enumerate(observables):
                values = [100.0 * block["models"][m]["relative_change_by_observable"][observable] for m in model_ids]
                ax.bar(positions + (index - len(observables) / 2) * width, values, width, label=OBSERVABLE_LABELS.get(observable, observable))
            pooled = [-100.0 * block["models"][m]["relative_improvement"] for m in model_ids]
            ax.bar(positions + (len(observables) / 2) * width, pooled, width, color="black", label="pooled (all observables)")
            ax.axhline(100.0 * data["maximum_observable_worsening"], color="tab:red", linestyle="--", linewidth=1, label="worsening limit")
            ax.axhline(-100.0 * data["minimum_relative_improvement"], color="tab:green", linestyle="--", linewidth=1, label="required pooled improvement")
            ax.axhline(0.0, color="grey", linewidth=0.8)
            ax.set_xticks(positions)
            ax.set_xticklabels(
                [f"{MODEL_LABELS.get(m, m)}\n({'passes' if block['models'][m]['passed'] else 'fails'} R1)" for m in model_ids], fontsize=8
            )
            ax.set_title(f"scenario: {scenario.replace('_', ' ')}", fontsize=10)
            ax.tick_params(labelsize=8)
        axes[0, 0].set_ylabel("change in pooled held-out error relative to M0 (percent; negative is better)", fontsize=8)
        axes[0, 0].legend(fontsize=7)
        fig.tight_layout()

    return PaperFigure(
        name="figure_3_criticism_screen",
        title="Stage A holdout screen of the model-criticism study",
        caption=(
            "Change in the pooled held-out normalised error of each candidate mechanism relative to the baseline M0, "
            "per observable and pooled, in both error scenarios; the dashed lines are the plan's screen thresholds "
            "(at least 10 percent pooled improvement, no observable more than 10 percent worse)."
        ),
        data=data,
        draw=draw,
        sources=_sources(root, [CRITICISM_STAGE_A, CRITICISM_PLAN]),
        key_numbers={
            "reference": reference,
            "passed": {
                scenario: {model_id: entry["passed"] for model_id, entry in block["models"].items()}
                for scenario, block in scenarios.items()
            },
            "relative_improvement": {
                scenario: {model_id: entry["relative_improvement"] for model_id, entry in block["models"].items()}
                for scenario, block in scenarios.items()
            },
        },
    )


# ---------------------------------------------------------------------------
# Figure 4: the cross-solver optimum check
# ---------------------------------------------------------------------------


def cross_solver_figure(root: Path) -> PaperFigure:
    comparison = _read_json(root / CROSS_SOLVER)
    gate = comparison["optimum_gate"]
    data = {
        "outcome": str(comparison["outcome"]),
        "reference_objective": float(gate["reference_objective"]),
        "local_fit_objective": float(gate["local_fit_objective"]),
        "copasi_best_objective": float(gate["copasi_best_objective"]),
        "copasi_best_source": str(gate["copasi_best_source"]),
        "start_objectives": [float(value) for value in gate["start_objectives"]],
        "fungmod_objective_at_copasi_best": float(comparison["cross_check_at_copasi_best"]["fungmod_objective"]),
        "simulation_worst_abs_difference_over_sigma": float(comparison["simulation_gate"]["worst_abs_difference_over_sigma"]),
    }

    def draw(data: dict[str, Any], fig: Any) -> None:
        ax = fig.subplots()
        starts = sorted(data["start_objectives"])
        ax.scatter(range(1, len(starts) + 1), starts, color="tab:orange", label="COPASI fits from random starts")
        ax.axhline(data["reference_objective"], color="black", linewidth=1.2, label="FungMod recorded optimum")
        ax.axhline(data["local_fit_objective"], color="tab:blue", linestyle="--", linewidth=1.2, label="COPASI fit from FungMod's optimum")
        ax.set_xlabel("random start (sorted by objective)", fontsize=9)
        ax.set_ylabel("PEtab objective (negative log-likelihood up to a constant)", fontsize=9)
        ax.set_yscale("log")
        ax.tick_params(labelsize=8)
        ax.legend(fontsize=8)
        fig.tight_layout()

    return PaperFigure(
        name="figure_4_cross_solver",
        title="Cross-solver check of the recorded optimum in COPASI",
        caption=(
            "Objective of the exported three-condition PEtab problem at FungMod's recorded optimum, after COPASI's "
            "local fit from that point, and at the end of COPASI's fits from ten random starts (log axis). The recorded "
            "outcome is quoted in the manifest."
        ),
        data=data,
        draw=draw,
        sources=_sources(root, [CROSS_SOLVER]),
        key_numbers={
            "outcome": data["outcome"],
            "reference_objective": data["reference_objective"],
            "copasi_best_objective": data["copasi_best_objective"],
            "relative_difference": float(gate["relative_difference"]),
            "starts": len(data["start_objectives"]),
            "simulation_worst_abs_difference_over_sigma": data["simulation_worst_abs_difference_over_sigma"],
        },
    )


FIGURE_BUILDERS: tuple[Callable[[Path], PaperFigure], ...] = (
    holdout_figure,
    posterior_predictive_figure,
    criticism_screen_figure,
    cross_solver_figure,
)
FIGURE_SIZES = {
    "figure_1_cellulose_holdouts": (11.0, 10.0),
    "figure_2_posterior_predictive": (11.0, 10.0),
    "figure_3_criticism_screen": (11.0, 5.0),
    "figure_4_cross_solver": (6.0, 4.0),
}


def build_figures(root: Path) -> list[PaperFigure]:
    return [builder(root) for builder in FIGURE_BUILDERS]


def manifest_for(figures: Sequence[PaperFigure]) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "generator": GENERATOR,
        "figures": {
            figure.name: {
                "file": figure.file_name,
                "pdf_file": figure.pdf_file_name,
                "data_file": figure.data_file_name,
                "title": figure.title,
                "caption": figure.caption,
                "sources": figure.sources,
                "key_numbers": figure.key_numbers,
            }
            for figure in figures
        },
    }


def render(figure: PaperFigure, path: Path, *, fmt: str = "svg", dpi: int = 150) -> None:
    """Draw ``figure`` with matplotlib and save it; SVG and PDF metadata carry the generator, never a date."""

    import matplotlib

    matplotlib.use("Agg", force=False)
    from matplotlib.figure import Figure

    fig = Figure(figsize=FIGURE_SIZES[figure.name])
    figure.draw(figure.data, fig)
    if fmt == "svg":
        metadata: dict[str, Any] = {"Creator": GENERATOR, "Date": None}
    elif fmt == "pdf":
        metadata = {"Creator": GENERATOR, "CreationDate": None, "ModDate": None}
    else:
        metadata = {"Software": GENERATOR}
    fig.savefig(path, format=fmt, dpi=dpi, metadata=metadata)


def write_figures(root: Path, directory: Path | None = None) -> dict[str, Any]:
    """Regenerate every figure, its data file and the manifest under ``directory`` (default ``paper/figures``)."""

    target = root / PAPER_FIGURES_DIR if directory is None else directory
    target.mkdir(parents=True, exist_ok=True)
    figures = build_figures(root)
    for figure in figures:
        (target / figure.data_file_name).write_text(figure.rendered_data(), encoding="utf-8")
        render(figure, target / figure.file_name)
        render(figure, target / figure.pdf_file_name, fmt="pdf")
    manifest = manifest_for(figures)
    (target / MANIFEST_NAME).write_text(json.dumps(manifest, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    return manifest


def check_figures(root: Path, directory: Path | None = None) -> list[str]:
    """Differences between the committed figure data and manifest and what the recorded results generate now."""

    target = root / PAPER_FIGURES_DIR if directory is None else directory
    problems: list[str] = []
    figures = build_figures(root)
    for figure in figures:
        data_path = target / figure.data_file_name
        if not data_path.exists():
            problems.append(f"{data_path} is missing")
        elif data_path.read_text(encoding="utf-8") != figure.rendered_data():
            problems.append(f"{data_path} differs from the data generated from the recorded results")
        svg_path = target / figure.file_name
        if not svg_path.exists():
            problems.append(f"{svg_path} is missing")
        elif GENERATOR not in svg_path.read_text(encoding="utf-8"):
            problems.append(f"{svg_path} does not carry the generator marker")
        pdf_path = target / figure.pdf_file_name
        if not pdf_path.exists():
            problems.append(f"{pdf_path} is missing")
        elif PDF_MARKER not in pdf_path.read_bytes():
            problems.append(f"{pdf_path} does not carry the generator marker")
    manifest_path = target / MANIFEST_NAME
    if not manifest_path.exists():
        problems.append(f"{manifest_path} is missing")
    else:
        recorded = json.loads(manifest_path.read_text(encoding="utf-8"))
        if recorded != manifest_for(figures):
            problems.append(f"{manifest_path} differs from the manifest generated from the recorded results")
        for name, entry in recorded.get("figures", {}).items():
            for source, digest in entry.get("sources", {}).items():
                path = root / source
                if not path.exists():
                    problems.append(f"{name}: source {source} is missing")
                elif file_digest(path) != digest:
                    problems.append(f"{name}: source {source} changed since the manifest was written")
    return problems


__all__ = [
    "FIGURE_BUILDERS",
    "GENERATOR",
    "MANIFEST_NAME",
    "PAPER_FIGURES_DIR",
    "PDF_MARKER",
    "PaperFigure",
    "build_figures",
    "check_figures",
    "criticism_screen_figure",
    "cross_solver_figure",
    "holdout_figure",
    "manifest_for",
    "posterior_predictive_figure",
    "render",
    "write_figures",
]
