"""Tables of the software paper, generated from the recorded study results with a digest manifest.

Every number the paper quotes about the Gelain 2020 studies comes from a
checksummed result file in ``data/benchmarks``. This module turns those files
into the paper's tables (Markdown under ``paper/tables``) together with a
manifest that records, for each table, the source files and their SHA-256
digests and the key numbers the text uses. ``scripts/reproduce_paper.py``
calls it; ``tests/test_paper_tables.py`` checks that regenerating the tables
reproduces the committed files byte for byte and that the manifest digests
match the sources on disk.

Nothing here computes science: it reads recorded results and formats them.
The verification helpers at the end recompute a few cheap quantities from the
recorded artifacts (digest chains, the compiled-core objective at the recorded
cross-solver optimum, the stationarity of the recorded stage A baseline fit)
so that a reader can check the recorded files without re-running the studies.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np

from fungal_model.research import gelain_bayesian, gelain_criticism, gelain_petab
from fungal_model.research.gelain_culture import CultureBenchmarkError

PAPER_TABLES_DIR = Path("paper/tables")
MANIFEST_NAME = "manifest.json"
JOINT_REPORT = Path("data/benchmarks/gelain_2020_v2/results/report.json")
JOINT_PLAN = Path("data/benchmarks/gelain_2020_v2/plan.json")
BAYESIAN_RESULT = Path("data/benchmarks/gelain_2020_bayesian/results/bayesian_calibration.json")
CRITICISM_STAGE_A = Path("data/benchmarks/gelain_2020_criticism/results/stage_a/comparison.json")
CRITICISM_STAGE_B = Path("data/benchmarks/gelain_2020_criticism/results/stage_b")
CROSS_SOLVER = Path("data/benchmarks/gelain_2020_petab/results/comparison.json")
SHORT_SYMBOLS = {
    "gelain_hydrolysis_k_h": "k_h",
    "gelain_hydrolysis_Kh": "Kh",
    "gelain_hydrolysis_Y": "Y",
    "gelain_hydrolysis_kd": "kd",
    "gelain_hydrolysis_K_ind": "K_ind",
    "gelain_hydrolysis_qF": "qF",
    "gelain_hydrolysis_kF": "kF",
    "gelain_hydrolysis_qB": "qB",
    "gelain_hydrolysis_kB": "kB",
    "noise_scale:all_observables": "noise multiplier",
}


def file_digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _read_json(path: Path) -> Any:
    if not path.exists():
        raise CultureBenchmarkError(f"Recorded result {path} is missing; the paper tables need it.")
    return json.loads(path.read_text(encoding="utf-8"))


def _short(symbol: str) -> str:
    return SHORT_SYMBOLS.get(symbol, symbol.replace("gelain_criticism_", ""))


def _pct(value: float) -> str:
    return f"{100.0 * value:+.1f}%"


@dataclass(frozen=True)
class PaperTable:
    """One table of the paper: its Markdown, the files it was read from and the numbers the text quotes."""

    name: str
    title: str
    markdown: str
    sources: dict[str, str] = field(default_factory=dict)
    key_numbers: dict[str, Any] = field(default_factory=dict)

    @property
    def file_name(self) -> str:
        return f"{self.name}.md"

    def rendered(self) -> str:
        return f"<!-- generated by scripts/reproduce_paper.py tables; do not edit -->\n# {self.title}\n\n{self.markdown}\n"


def _sources(root: Path, paths: Sequence[Path]) -> dict[str, str]:
    return {path.as_posix(): file_digest(root / path) for path in paths}


# ---------------------------------------------------------------------------
# Table 1: whole-condition holdouts of the joint benchmark (v2)
# ---------------------------------------------------------------------------


def joint_benchmark_table(root: Path) -> PaperTable:
    report = _read_json(root / JOINT_REPORT)
    rows = report["comparison"]
    lines = [
        "| Family | Model | Scenario | Parameters | Practical rank | Mean normalized held-out MSE | Complexity screen |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        lines.append(
            f"| {row['family']} | {row['model']} | {row['scenario']} | {row['parameter_count']} | {row['practical_rank']} | "
            f"{row['mean_normalized_mse']:.4g} | {'passed' if row['complexity_screen_passed'] else 'failed'} |"
        )
    primary = {(row["family"], row["model"]): row for row in rows if row["scenario"] == "primary"}
    hydrolysis = primary[("cellulose", "hydrolysis")]
    published = primary[("cellulose", "published")]
    lines.extend(
        [
            "",
            f"Folds that passed the numerical checks: {report['successful_numerically_checked_folds']} of {report['folds']}; "
            f"optimiser starts that failed: {report['failed_starts']} of {report['optimizer_starts']}. "
            f"Validated: {report['validated']} (retrospective comparison on published means).",
        ]
    )
    return PaperTable(
        name="table_1_joint_holdouts",
        title="Whole-condition holdouts of the joint Gelain 2020 benchmark (v2)",
        markdown="\n".join(lines),
        sources=_sources(root, [JOINT_REPORT, JOINT_PLAN]),
        key_numbers={
            "hydrolysis_primary_mean_normalized_mse": hydrolysis["mean_normalized_mse"],
            "published_primary_mean_normalized_mse": published["mean_normalized_mse"],
            "published_parameter_count": published["parameter_count"],
            "published_practical_rank": published["practical_rank"],
            "published_screen_passed": published["complexity_screen_passed"],
            "hydrolysis_screen_passed_by_scenario": {
                row["scenario"]: row["complexity_screen_passed"] for row in rows if (row["family"], row["model"]) == ("cellulose", "hydrolysis")
            },
            "folds_numerically_checked": report["successful_numerically_checked_folds"],
            "folds": report["folds"],
            "failed_starts": report["failed_starts"],
            "optimizer_starts": report["optimizer_starts"],
            "validated": report["validated"],
        },
    )


# ---------------------------------------------------------------------------
# Table 2: identifiability of the registry constants (BAYES-001)
# ---------------------------------------------------------------------------


def identifiability_table(root: Path) -> PaperTable:
    result = _read_json(root / BAYESIAN_RESULT)
    diagnostics = result["diagnostics"]
    order = list(result["summaries"])
    taus = diagnostics["integrated_autocorrelation_time"]
    ess = diagnostics["effective_sample_size"]
    lines = [
        "| Constant | Class | Posterior median | 95% interval | Prior box | Width / prior width (log10) | tau | ESS |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    widths = []
    for symbol, verdict in result["identifiability"].items():
        summary = result["summaries"][symbol]
        index = order.index(symbol)
        interval = verdict["credible_interval"]
        prior = verdict["prior_bounds"]
        lines.append(
            f"| `{_short(symbol)}` | {verdict['class']} | {summary['median']:.4g} | [{interval[0]:.3g}, {interval[1]:.3g}] | "
            f"[{prior[0]:.3g}, {prior[1]:.3g}] | {verdict['interval_width_fraction_of_prior']:.2f} | {taus[index]:.0f} | {ess[index]:.0f} |"
        )
        if verdict["class"] == "identified":
            widths.append(verdict["interval_width_fraction_of_prior"])
    multiplier = result["summaries"]["noise_scale:all_observables"]
    settings = result["settings"]
    lines.extend(
        [
            "",
            f"Shared noise multiplier: median {multiplier['median']:.3g}, 95% interval [{multiplier['lower']:.3g}, {multiplier['upper']:.3g}] "
            f"at an assumed 10 percent error. Sampler: {settings['n_walkers']} walkers, {settings['n_steps']} steps, "
            f"{settings['burn_in']} burn-in; converged by the declared rule: {result['converged']}; "
            f"mean acceptance {diagnostics['mean_acceptance_fraction']:.3f}; effective sample sizes {min(ess):.0f} to {max(ess):.0f}.",
        ]
    )
    classes = {_short(symbol): verdict["class"] for symbol, verdict in result["identifiability"].items()}
    return PaperTable(
        name="table_2_identifiability",
        title="Identifiability of the nine registry constants of the hydrolysis candidate (BAYES-001)",
        markdown="\n".join(lines),
        sources=_sources(root, [BAYESIAN_RESULT, gelain_bayesian.PLAN_PATH]),
        key_numbers={
            "classes": classes,
            "identified_count": sum(1 for klass in classes.values() if klass == "identified"),
            "identified_width_fraction_range": [min(widths), max(widths)] if widths else None,
            "noise_multiplier": {"median": multiplier["median"], "lower": multiplier["lower"], "upper": multiplier["upper"]},
            "converged": result["converged"],
            "walkers": settings["n_walkers"],
            "steps": settings["n_steps"],
            "burn_in": settings["burn_in"],
            "effective_sample_size_range": [min(ess), max(ess)],
            "mean_acceptance": diagnostics["mean_acceptance_fraction"],
        },
    )


# ---------------------------------------------------------------------------
# Table 3: stage A of the model-criticism study
# ---------------------------------------------------------------------------


def criticism_stage_a_table(root: Path) -> PaperTable:
    comparison = _read_json(root / CRITICISM_STAGE_A)
    models = comparison["models"]
    baseline = models[gelain_criticism.BASELINE_MODEL]["scenarios"]
    lines = [
        "| Model | Scenario | Mean normalized held-out MSE | Change vs M0 | Full rank everywhere | Screen (R1) |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    key: dict[str, Any] = {"plan_sha256": comparison["inputs"]["plan_sha256"], "optimiser": comparison["inputs"].get("optimiser"), "models": {}}
    for model_id, summary in models.items():
        key["models"][model_id] = {}
        for scenario, item in summary["scenarios"].items():
            screen = item["screen"]
            change = screen.get("relative_improvement")
            lines.append(
                f"| {model_id} | {scenario} | {item['mean_normalized_mse']:.4g} | {'' if change is None else _pct(change)} | "
                f"{item['full_rank_everywhere']} | {'passed' if screen['passed'] else 'failed: ' + '; '.join(screen['reasons'])} |"
            )
            key["models"][model_id][scenario] = {
                "mean_normalized_mse": item["mean_normalized_mse"],
                "relative_improvement": change,
                "screen_passed": screen["passed"],
                "per_observable_change": {
                    name: item["pooled_normalized_mse"][name] / baseline[scenario]["pooled_normalized_mse"][name] - 1.0
                    for name in item["pooled_normalized_mse"]
                }
                if model_id != gelain_criticism.BASELINE_MODEL
                else None,
            }
    observables = list(baseline["primary"]["pooled_normalized_mse"])
    lines.extend(["", "Per-observable pooled normalized held-out MSE, primary scenario:", "", "| Model | " + " | ".join(observables) + " |", "| --- | " + " | ".join("---" for _ in observables) + " |"])
    for model_id, summary in models.items():
        item = summary["scenarios"]["primary"]
        lines.append(f"| {model_id} | " + " | ".join(f"{item['pooled_normalized_mse'][name]:.4g}" for name in observables) + " |")
    return PaperTable(
        name="table_3_criticism_stage_a",
        title="Stage A of the preregistered model-criticism study: whole-condition holdouts and the R1 screen",
        markdown="\n".join(lines),
        sources=_sources(root, [CRITICISM_STAGE_A, gelain_criticism.PLAN_PATH]),
        key_numbers=key,
    )


# ---------------------------------------------------------------------------
# Table 4: stage B verdicts of the model-criticism study
# ---------------------------------------------------------------------------


def criticism_stage_b_table(root: Path) -> PaperTable:
    stage_b = root / CRITICISM_STAGE_B
    folders = sorted(path.parent for path in stage_b.glob("*/verdicts.json")) if stage_b.exists() else []
    if not folders:
        raise CultureBenchmarkError(f"No recorded stage B posterior under {stage_b}.")
    lines = [
        "| Model | Chain | Converged | R1 holdout | R2 multiplier interval | R3 added-parameter classes | Coverage (95%, with noise) | Outcome |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    sources: list[Path] = [gelain_criticism.PLAN_PATH]
    key: dict[str, Any] = {}
    for folder in folders:
        verdicts = _read_json(folder / "verdicts.json")
        calibration = _read_json(folder / "bayesian_calibration.json")
        coverage = _read_json(folder / "coverage.json")
        settings = calibration["settings"]
        diagnostics = calibration["diagnostics"]
        interval = verdicts["R2_multiplier_interval"]
        classes = verdicts["added_parameter_classes"]
        overall = coverage.get("overall", {}).get("all_observables")
        lines.append(
            f"| {folder.name} | {settings['n_walkers']} walkers x {settings['n_steps']} steps | {calibration['converged']} | "
            f"{verdicts['R1_holdout_support']} | [{interval[0]:.3g}, {interval[1]:.3g}] | "
            + ", ".join(f"`{name}` {klass}" for name, klass in classes.items())
            + f" | {overall['inside']}/{overall['observations']} | {verdicts['outcome']}{' (provisional)' if verdicts['provisional'] else ''} |"
        )
        for name in ("verdicts.json", "bayesian_calibration.json", "coverage.json"):
            sources.append((folder / name).relative_to(root))
        key[folder.name] = {
            "converged": calibration["converged"],
            "provisional": verdicts["provisional"],
            "R1_holdout_support": verdicts["R1_holdout_support"],
            "R2_adequacy": verdicts["R2_adequacy"],
            "R2_multiplier_interval": interval,
            "R3_identification": verdicts["R3_identification"],
            "added_parameter_classes": classes,
            "coverage_inside": overall["inside"],
            "coverage_observations": overall["observations"],
            "largest_autocorrelation_time": max(diagnostics["integrated_autocorrelation_time"]),
            "post_burn_in_steps": diagnostics["post_burn_in_steps"],
            "outcome": verdicts["outcome"],
        }
    lines.extend(["", "M0 is the baseline: its all-condition posterior is BAYES-001 (Table 2), which R1 and R3 do not address."])
    return PaperTable(
        name="table_4_criticism_stage_b",
        title="Stage B of the model-criticism study: adequacy, identification and coverage per added mechanism",
        markdown="\n".join(lines),
        sources=_sources(root, sources),
        key_numbers=key,
    )


# ---------------------------------------------------------------------------
# Table 5: cross-solver reproduction (PEtab, COPASI)
# ---------------------------------------------------------------------------


def cross_solver_table(root: Path) -> PaperTable:
    comparison = _read_json(root / CROSS_SOLVER)
    simulation = comparison["simulation_gate"]
    optimum = comparison["optimum_gate"]
    cross = comparison["cross_check_at_copasi_best"]
    lines = [
        "| Quantity | Value |",
        "| --- | --- |",
        f"| Worst abs(COPASI - FungMod) / sigma at FungMod's optimum | {simulation['worst_abs_difference_over_sigma']:.2g} |",
        f"| Objective relative difference at FungMod's optimum | {simulation['objective_relative_difference']:.2g} |",
        f"| FungMod objective (reference) | {optimum['reference_objective']:.9g} |",
        f"| COPASI best objective ({optimum['copasi_best_source']}) | {optimum['copasi_best_objective']:.9g} |",
        f"| Relative difference of the optima | {optimum['relative_difference']:.2g} |",
        f"| Best of the random starts | {min(optimum['start_objectives']):.6g} (of {len(optimum['start_objectives'])}) |",
        f"| FungMod at COPASI's best point | {cross['fungmod_objective']:.9g} (relative difference {cross['relative_difference']:.2g}) |",
        f"| Simulation gate / optimum gate | {simulation['passed']} / {optimum['passed']} |",
        f"| Outcome | `{comparison['outcome']}` |",
        "",
        "| Parameter | FungMod | COPASI best | Relative difference |",
        "| --- | --- | --- | --- |",
    ]
    for entry in comparison["parameters"]:
        lines.append(f"| `{entry['symbol']}` | {entry['fungmod']:.4g} | {entry['copasi']:.4g} | {entry['relative_difference']:.2g} |")
    return PaperTable(
        name="table_5_cross_solver",
        title="Cross-solver reproduction of the baseline optimum in COPASI through PEtab (PETAB-001, second run)",
        markdown="\n".join(lines),
        sources=_sources(root, [CROSS_SOLVER, gelain_petab.PLAN_PATH]),
        key_numbers={
            "outcome": comparison["outcome"],
            "plan_sha256": comparison["plan_sha256"],
            "worst_abs_difference_over_sigma": simulation["worst_abs_difference_over_sigma"],
            "objective_relative_difference_at_optimum": simulation["objective_relative_difference"],
            "reference_objective": optimum["reference_objective"],
            "copasi_best_objective": optimum["copasi_best_objective"],
            "optimum_relative_difference": optimum["relative_difference"],
            "largest_parameter_relative_difference": max(entry["relative_difference"] for entry in comparison["parameters"]),
        },
    )


TABLE_BUILDERS: tuple[Callable[[Path], PaperTable], ...] = (
    joint_benchmark_table,
    identifiability_table,
    criticism_stage_a_table,
    criticism_stage_b_table,
    cross_solver_table,
)


def build_tables(root: Path) -> list[PaperTable]:
    return [builder(root) for builder in TABLE_BUILDERS]


def manifest_for(tables: Sequence[PaperTable]) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "generator": "fungal_model.research.paper_tables (scripts/reproduce_paper.py tables)",
        "tables": {
            table.name: {
                "file": table.file_name,
                "title": table.title,
                "sources": table.sources,
                "key_numbers": table.key_numbers,
            }
            for table in tables
        },
    }


def write_tables(root: Path, directory: Path | None = None) -> dict[str, Any]:
    """Regenerate every table and the manifest under ``directory`` (default ``paper/tables``)."""

    target = root / PAPER_TABLES_DIR if directory is None else directory
    target.mkdir(parents=True, exist_ok=True)
    tables = build_tables(root)
    for table in tables:
        (target / table.file_name).write_text(table.rendered(), encoding="utf-8")
    manifest = manifest_for(tables)
    (target / MANIFEST_NAME).write_text(json.dumps(manifest, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    return manifest


def check_tables(root: Path, directory: Path | None = None) -> list[str]:
    """Differences between the committed tables and what the recorded results generate now (empty when consistent)."""

    target = root / PAPER_TABLES_DIR if directory is None else directory
    problems: list[str] = []
    tables = build_tables(root)
    for table in tables:
        path = target / table.file_name
        if not path.exists():
            problems.append(f"{path} is missing")
        elif path.read_text(encoding="utf-8") != table.rendered():
            problems.append(f"{path} differs from the table generated from the recorded results")
    manifest_path = target / MANIFEST_NAME
    if not manifest_path.exists():
        problems.append(f"{manifest_path} is missing")
    else:
        recorded = json.loads(manifest_path.read_text(encoding="utf-8"))
        if recorded != manifest_for(tables):
            problems.append(f"{manifest_path} differs from the manifest generated from the recorded results")
        for name, entry in recorded.get("tables", {}).items():
            for source, digest in entry.get("sources", {}).items():
                path = root / source
                if not path.exists():
                    problems.append(f"{name}: source {source} is missing")
                elif file_digest(path) != digest:
                    problems.append(f"{name}: source {source} changed since the manifest was written")
    return problems


# ---------------------------------------------------------------------------
# Cheap verification of the recorded results (no study is re-run)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Check:
    name: str
    passed: bool
    detail: str


def _digest_chain(plan: Mapping[str, Any], plan_path: Path) -> set[str]:
    return {file_digest(plan_path), *(entry["previous_sha256"] for entry in plan.get("amendments", []))}


def verify_recorded_results(root: Path, *, registry: Any = None) -> list[Check]:
    """Recompute what can be recomputed in minutes from the recorded artifacts.

    Digest chains of every study against its plan; the frozen held-out
    predictions and the stage B artifact digests; the cross-solver plan's
    sources; the compiled-core objective at the recorded cross-solver
    optimum (must equal the recorded reference to 1e-7); and the projected
    cost gradient of the recorded stage A baseline fit (must be below 1e-2
    in log space, the stationarity the amendment 3 re-run established).
    """

    checks: list[Check] = []

    def record(name: str, passed: bool, detail: str) -> None:
        checks.append(Check(name, bool(passed), detail))

    # criticism plan chain and stage A files
    plan = gelain_criticism.load_plan(root)
    chain = _digest_chain(plan, root / gelain_criticism.PLAN_PATH)
    comparison = _read_json(root / CRITICISM_STAGE_A)
    record("criticism stage A cites the plan chain", comparison["inputs"]["plan_sha256"] in chain, comparison["inputs"]["plan_sha256"][:12])
    frozen_ok, frozen_count = True, 0
    for model_id in comparison["models"]:
        for scenario in comparison["models"][model_id]["scenarios"]:
            folds = _read_json(root / CRITICISM_STAGE_A.parent / model_id / f"folds_{scenario}.json")
            for fold in folds:
                frozen_path = root / CRITICISM_STAGE_A.parent.parent / fold["frozen_prediction_file"]
                frozen_count += 1
                if not frozen_path.exists() or file_digest(frozen_path) != fold["frozen_prediction_sha256"]:
                    frozen_ok = False
    record("stage A frozen held-out predictions match their recorded digests", frozen_ok, f"{frozen_count} files")
    stage_b = root / CRITICISM_STAGE_B
    artifacts_ok, artifact_count = True, 0
    for artifacts_path in sorted(stage_b.glob("**/artifacts.json")) if stage_b.exists() else []:
        folder = artifacts_path.parent
        inputs = _read_json(folder / "inputs.json")
        if inputs["plan_sha256"] not in chain:
            artifacts_ok = False
        for name, digest in _read_json(artifacts_path).items():
            if name == "artifacts.json":
                continue
            artifact_count += 1
            if not (folder / name).exists() or file_digest(folder / name) != digest:
                artifacts_ok = False
    record("stage B artifacts match their recorded digests and cite the plan chain", artifacts_ok, f"{artifact_count} files")

    # Bayesian study
    bayesian_inputs = _read_json(root / gelain_bayesian.PLAN_PATH.parent / "results" / "inputs.json")
    bayesian_plan_digest = file_digest(root / gelain_bayesian.PLAN_PATH)
    record("BAYES-001 cites the current Bayesian plan", bayesian_inputs["plan_sha256"] == bayesian_plan_digest, bayesian_plan_digest[:12])
    bayesian_artifacts = _read_json(root / gelain_bayesian.PLAN_PATH.parent / "results" / "artifacts.json")
    ok = all(
        file_digest(root / gelain_bayesian.PLAN_PATH.parent / "results" / name) == digest
        for name, digest in bayesian_artifacts.items()
        if name != "artifacts.json" and (root / gelain_bayesian.PLAN_PATH.parent / "results" / name).exists()
    )
    record("BAYES-001 artifacts match their recorded digests", ok, f"{len(bayesian_artifacts)} entries")

    # cross-solver plan and the compiled-core objective at the recorded optimum
    petab_plan = gelain_petab.load_plan(root)
    try:
        gelain_petab.verify_sources(root, petab_plan)
        record("cross-solver plan sources carry their frozen digests", True, "4 sources")
    except CultureBenchmarkError as exc:
        record("cross-solver plan sources carry their frozen digests", False, str(exc))
    cross = _read_json(root / CROSS_SOLVER)
    record("cross-solver result cites the current plan", cross["plan_sha256"] == file_digest(root / gelain_petab.PLAN_PATH), cross["plan_sha256"][:12])
    import tempfile

    with tempfile.TemporaryDirectory() as temporary:
        problem = gelain_petab.build_problem(root, Path(temporary), registry=registry)
        objective = problem.fungmod_objective()
    reference = cross["optimum_gate"]["reference_objective"]
    relative = abs(objective - reference) / reference
    record("compiled-core objective at the recorded cross-solver optimum", relative <= 1e-7, f"{objective:.9g} against {reference:.9g} (relative {relative:.1e})")

    # stationarity of the recorded stage A baseline fit
    fit = gelain_petab.reference_fit(root, petab_plan)
    gradient_norm = projected_gradient_norm(root, fit, registry=registry)
    record("recorded stage A baseline fit is stationary (projected gradient norm in log space)", gradient_norm < 1e-2, f"{gradient_norm:.2e}")
    return checks


def projected_gradient_norm(root: Path, fit: Mapping[str, Any], *, registry: Any = None) -> float:
    """Norm of the stage A primary cost gradient at a recorded M0 fit, with outward components on active bounds removed."""

    from fungal_model.registry import load_registry

    plan = gelain_criticism.load_plan(root)
    bayesian_plan = gelain_bayesian.load_plan(root)
    store = registry if registry is not None else load_registry(root / gelain_criticism.REGISTRY_INDEX)
    conditions = gelain_criticism.observed_conditions(root, plan)
    variant = gelain_criticism.model_variants(plan)[gelain_criticism.BASELINE_MODEL]
    predictor = gelain_criticism.build_predictor(store, plan, gelain_criticism.BASELINE_MODEL, bayesian_plan=bayesian_plan)
    scales = gelain_criticism.training_scales(conditions)
    free = list(variant.parameters)
    lower, upper = variant.log_bounds()

    def cost(log_values: np.ndarray) -> float:
        values = {spec.symbol: float(value) for spec, value in zip(free, np.exp(log_values), strict=True)}
        config_values = variant.config_values(values)
        residuals = np.concatenate(
            [((predictor.predict_values(config_values, c.condition_id, c.times) - c.observed) / scales).ravel() for c in conditions]
        )
        return 0.5 * float(residuals @ residuals)

    point = np.log([float(entry["value"]) for entry in fit["parameters"]])
    step = float(plan["stage_A_least_squares"]["optimiser"]["log_parameter_difference_step"])
    gradient = np.zeros_like(point)
    for index in range(point.size):
        unit = np.zeros_like(point)
        unit[index] = step
        gradient[index] = (cost(point + unit) - cost(point - unit)) / (2.0 * step)
    on_lower = (point - lower < 1e-6) & (gradient > 0.0)
    on_upper = (upper - point < 1e-6) & (gradient < 0.0)
    return float(np.linalg.norm(np.where(on_lower | on_upper, 0.0, gradient)))


__all__ = [
    "Check",
    "MANIFEST_NAME",
    "PAPER_TABLES_DIR",
    "PaperTable",
    "TABLE_BUILDERS",
    "build_tables",
    "check_tables",
    "criticism_stage_a_table",
    "criticism_stage_b_table",
    "cross_solver_table",
    "identifiability_table",
    "joint_benchmark_table",
    "manifest_for",
    "projected_gradient_norm",
    "verify_recorded_results",
    "write_tables",
]
